# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build client image
      inputs:
        containerRegistry: 'footan_dockerhub'
        repository: 'footan/react_client'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/services/client/dockerfile.dev'
        buildContext: '$(Build.SourcesDirectory)/src/services/client/'
        tags: |
          $(tag)
