apiVersion: skaffold/v2beta13
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: thegreatneuron/auth
      context: ./src/services/auth
      docker:
        dockerfile: dockerfile.dev
      sync:
        manual:
          - src: '/**/*.cs'
            dest: .