FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY ["[project-name]/src/API/API.csproj", "[project-name]/src/API/"]
COPY ["[project-name]/src/Application/Application.csproj", "[project-name]/src/Application/"]
COPY ["[project-name]/src/Infrastructure/Infrastructure.csproj", "[project-name]/src/Infrastructure/"]
COPY ["[project-name]/src/Domain/Domain.csproj", "[project-name]/src/Domain/"]
#COPY ["common/src/Common.API/Common.API.csproj", "common/src/Common.API/"]
#COPY ["common/src/Common.Application/Common.Application.csproj", "common/src/Common.Application/"]
#COPY ["common/src/Common.Domain/Common.Domain.csproj", "common/src/Common.Domain/"]
#COPY ["common/src/Common.Infrastructure/Common.Infrastructure.csproj", "common/src/Common.Infrastructure/"]

RUN dotnet restore "[project-name]/src/API/API.csproj"
COPY . .
WORKDIR /app/[project-name]/src/API/
RUN dotnet build "API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0
EXPOSE 80
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.dll"]