ingress:
  className: ""
  annotations: {
     kubernetes.io/ingress.class: nginx,
     nginx.ingress.kubernetes.io/use-regex: "true"
  }
  hosts:
    - host: localhost
      paths:
        - path: /admin/?(.*)
          pathType: Prefix
          port: 8001
          name: admin

        - path: /api/auth/?(.*)
          pathType: Prefix
          port: 8002
          name: auth

        - path: /api/article/?(.*)
          pathType: Prefix
          port: 8003
          name: article

        - path: /?(.*)
          pathType: Prefix
          port: 8000
          name: client