#version 1.0.1
FROM node:16-alpine3.11 AS build
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
RUN npm run build
## ---
FROM node:12.17.0-alpine
WORKDIR /usr
COPY package.json ./
RUN npm install --only=production
COPY --from=build /usr/dist .
RUN npm install pm2 -g
ENV PORT=80
EXPOSE 80
ENV RUNTIME_ENVIRONMENT=production
CMD ["pm2-runtime","app.js"]