FROM node:latest AS build
WORKDIR /build

COPY package.json .
COPY tsconfig.json .
RUN npm install

COPY public/ public
COPY src/ src
RUN npm run build

FROM nginx:alpine
COPY --from=build /build/build/ /usr/share/nginx/html